### PR TITLE
FIO-1308: Upgrade to vue 3

### PR DESCRIPTION
**Pull request by RomanLetsuk**

### CODE REVIEW

**Comment by aminmc** [comment]
@travist Is it possible to get this merged? I'd like to use formio with vue 3

**Comment by plitton** [comment]
> @travist Is it possible to get this merged? I'd like to use formio with vue 3

Also looking to get this merged. I'd like to see this working with vue 3 ASAP

**Comment by androiddrew** [comment]
Ooof! I came to evaluate formio for a vue project. Probably not a good fit though it PRs are sitting out here for modern vue for far too long :(

**Comment by travist** [comment]
We have been using this library with the modern vue without issues. I will have one of my Vue developers look at it next week and see why this has not been merged. If I knew more about Vue, I would do it myself, but I just need to get an approval from one of my devs.

**Comment by travist** [comment]
Done in another PR.

This will be done for ```@formio/vue@5.0.0-rc.1```

**Comment by APavlov2** [comment]
@travist when will `@formio/vue@5.0.0-rc.1` be available?

**Comment by hisuwh** [comment]
@travist have you got a link to the other PR so we can track this?
I see [5.0.0-rc.1](https://www.npmjs.com/package/@formio/vue/v/5.0.0-rc.1) on npm - is there an ETA for this to be GA?

**Pull request closed without merging**
